/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2018-03-06 14:08:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminlogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1507536606000L));
    _jspx_dependants.put("jar:file:/S:/StudentUpdated/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/StudentFeedBackSystem/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--\r\n");
      out.write("Template Name: Academic Education V2\r\n");
      out.write("Author: <a href=\"http://www.os-templates.com/\">OS Templates</a>\r\n");
      out.write("Author URI: http://www.os-templates.com/\r\n");
      out.write("Licence: Free to use under our free template licence terms\r\n");
      out.write("Licence URI: http://www.os-templates.com/template-terms\r\n");
      out.write("-->\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("<script \r\n");
      out.write("src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>  \r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write("   function preventBack()\r\n");
      out.write("   {\r\n");
      out.write("\t   //alert(\"hiiiiiiiiiiiiii\");\r\n");
      out.write("\t   window.history.forward();\r\n");
      out.write("   }\r\n");
      out.write("   setTimeout(\"preventBack()\",0);\r\n");
      out.write("   window.onunload = function()\r\n");
      out.write("   {\r\n");
      out.write("\t   null\r\n");
      out.write("   };\r\n");
      out.write("   </script>\r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("   function displaymsg()\r\n");
      out.write("   {\r\n");
      out.write("\t   var email=$('#mail').val();\r\n");
      out.write("\t   var password=$('#name').val();\r\n");
      out.write("\t   $.ajax({\r\n");
      out.write("\t\t  url:'UserServlet',\r\n");
      out.write("\t\t  method:'POST',\r\n");
      out.write("\t\t  data:{action:\"Login\",email:email,password:password},\r\n");
      out.write("\t\t  success:function(data)\r\n");
      out.write("\t\t  {\r\n");
      out.write("\t   \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t\t  alert(\"Invalid UserName and Password\");\r\n");
      out.write("\t\t\t  $('#mail').val(\"\");\r\n");
      out.write("\t\t\t  $('#name').val(\"\");\r\n");
      out.write("\t\t\t  return false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t  }\r\n");
      out.write("\t   \r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t   \r\n");
      out.write("\t   });\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   </script>\r\n");
      out.write("<title>Academic Education V2</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">\r\n");
      out.write("<link href=\"layout/styles/layout.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\">\r\n");
      out.write(" \r\n");
      out.write(" \t\t <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css\">\r\n");
      out.write("     \t <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\t\t<meta charset=\"utf-8\" name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/normalize.css\">\r\n");
      out.write("        <link href='https://fonts.googleapis.com/css?family=Nunito:400,300' rel='stylesheet' type='text/css'>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/main.css\">\r\n");
      out.write("     \r\n");
      out.write("<style>\r\n");
      out.write("ul li{\r\n");
      out.write("font-size:15px;\r\n");
      out.write("}\r\n");
      out.write("</style>     \r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"top\">\r\n");
      out.write("<!-- ################################################################################################ -->\r\n");
      out.write("<div class=\"wrapper row0\">\r\n");
      out.write("  <div id=\"topbar\" class=\"clear\"> \r\n");
      out.write("    <!-- ################################################################################################ -->\r\n");
      out.write("    <!-- ################################################################################################ --> \r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ################################################################################################ -->    \r\n");
      out.write("<!-- ################################################################################################ -->\r\n");
      out.write("<div class=\"wrapper row2\">\r\n");
      out.write("  <div class=\"rounded\">\r\n");
      out.write("    <nav id=\"mainav\" class=\"clear\"> \r\n");
      out.write("      <!-- ################################################################################################ -->\r\n");
      out.write("      <ul class=\"clear\">\r\n");
      out.write("        <li class=\"active\"><a href=\"home.jsp\">Home</a></li>\r\n");
      out.write("         \r\n");
      out.write("       <!--  <li><a href=\"login.jsp\">Admin Login</a></li>\r\n");
      out.write("        <li><a href=\"login.jsp\">Staff Login</a></li>\r\n");
      out.write("        <li><a href=\"login.jsp\">Student Login</a></li> -->\r\n");
      out.write("     <!--    <li><a href=\"#\">Log out</a></li> -->\r\n");
      out.write("      </ul>\r\n");
      out.write("      <!-- ################################################################################################ --> \r\n");
      out.write("    </nav>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ################################################################################################ --> \r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <form action=\"UserServlet\" method=\"post\">   \r\n");
      out.write("        <fieldset>\r\n");
      out.write("         <label>\r\n");
      out.write("        ");

		String loginmsg=(String)request.getAttribute("error");
		if(loginmsg!=null)
		out.println("<font color=green size=4px>"+loginmsg+"</font>");		
		
      out.write("\r\n");
      out.write("\t\t</label>\r\n");
      out.write("          <legend><span class=\"number\"></span>Sign In</legend>\r\n");
      out.write("            \r\n");
      out.write("          <label for=\"mail\">Email:</label>\r\n");
      out.write("          <input type=\"email\" id=\"mail\" name=\"email\" required=\"\" placeholder=\"xyz@gmail.com\">\r\n");
      out.write("          \r\n");
      out.write("          <label for=\"name\">Password:</label>\r\n");
      out.write("          <input type=\"password\" id=\"name\" name=\"password\" required=\"\" placeholder=\"xyz@123\">\r\n");
      out.write("          \r\n");
      out.write("        </fieldset>\r\n");
      out.write("         <button type=\"submit\" name=\"action\" value=\"adminLogin\">Submit</button>  \r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("       </form> \r\n");
      out.write(" \r\n");
      out.write("   <!-- JAVASCRIPTS --> \r\n");
      out.write("<script src=\"layout/scripts/jquery.min.js\"></script> \r\n");
      out.write("<script src=\"layout/scripts/jquery.fitvids.min.js\"></script> \r\n");
      out.write("<script src=\"layout/scripts/jquery.mobilemenu.js\"></script> \r\n");
      out.write("<script src=\"layout/scripts/tabslet/jquery.tabslet.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
