/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2018-03-15 11:00:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class allstudentlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1507536606000L));
    _jspx_dependants.put("jar:file:/S:/StudentUpdated/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/StudentFeedBackSystem/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--\r\n");
      out.write("Template Name: Academic Education V2\r\n");
      out.write("Author: <a href=\"http://www.os-templates.com/\">OS Templates</a>\r\n");
      out.write("Author URI: http://www.os-templates.com/\r\n");
      out.write("Licence: Free to use under our free template licence terms\r\n");
      out.write("Licence URI: http://www.os-templates.com/template-terms\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css\"> -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write(" \t\t<link href='https://fonts.googleapis.com/css?family=Nunito:400,300' rel='stylesheet' type='text/css'>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/main.css\">\r\n");
      out.write("        <link href=\"layout/styles/layout.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\">\r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write("   function preventBack()\r\n");
      out.write("   {\r\n");
      out.write("\t   //alert(\"hiiiiiiiiiiiiii\");\r\n");
      out.write("\t   window.history.forward();\r\n");
      out.write("   }\r\n");
      out.write("   setTimeout(\"preventBack()\",0);\r\n");
      out.write("   window.onunload = function()\r\n");
      out.write("   {\r\n");
      out.write("\t   null\r\n");
      out.write("   };\r\n");
      out.write("   </script>\r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("   function displaymsg()\r\n");
      out.write("   {\r\n");
      out.write("\t   var email=$('#mail').val();\r\n");
      out.write("\t   var password=$('#name').val();\r\n");
      out.write("\t   $.ajax({\r\n");
      out.write("\t\t  url:'UserServlet',\r\n");
      out.write("\t\t  method:'POST',\r\n");
      out.write("\t\t  data:{action:\"Login\",email:email,password:password},\r\n");
      out.write("\t\t  success:function(data)\r\n");
      out.write("\t\t  {\r\n");
      out.write("\t   \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t\t  alert(\"Invalid UserName and Password\");\r\n");
      out.write("\t\t\t  $('#mail').val(\"\");\r\n");
      out.write("\t\t\t  $('#name').val(\"\");\r\n");
      out.write("\t\t\t  return false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t  }\r\n");
      out.write("\t   \r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t   \r\n");
      out.write("\t   });\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   </script>\r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\tfunction updateDetails(counter)\r\n");
      out.write("\t{\r\n");
      out.write("  \t var student_id =$(\"#studentID\"+counter).text();\r\n");
      out.write("  \t \r\n");
      out.write("      \t $.ajax({\r\n");
      out.write("      \t\t type:\"POST\",\r\n");
      out.write("      \t\t url : \"UserServlet\",\r\n");
      out.write("      \t\t data : {student_id:student_id , action:\"studentDetailsONID\"},\r\n");
      out.write("      \t\t success : function(data)\r\n");
      out.write("      \t\t{\r\n");
      out.write("      \t\t\t if(data!=0)\r\n");
      out.write("\t \t\t\t\t {\r\n");
      out.write("      \t\t\t\t\r\n");
      out.write("      \t\t\t\t\r\n");
      out.write("      \t\t\t $(\"#student_id\").val(data.student_id);\r\n");
      out.write("   \t\t\t\t $(\"#student_name\").val(data.student_name);\r\n");
      out.write("   \t\t\t\t $(\"#department\").val(data.student_department);\r\n");
      out.write("   \t\t\t\t $(\"#year\").val(data.year);\r\n");
      out.write("   \t\t\t\t $(\"#mobile\").val(data.mobile);\r\n");
      out.write("   \t\t\t\t $(\"#address\").val(data.address);\r\n");
      out.write("   \t\t\t\t $(\"#email\").val(data.email); \r\n");
      out.write("   \t\t\t\t\r\n");
      out.write("   \t\t\t\t\r\n");
      out.write("      \t\t\t\t\r\n");
      out.write("   \t\t\t  $(\"#myModal\").modal(\"show\");\r\n");
      out.write("\t \t\t\t\t\r\n");
      out.write("\t \t\t\t\r\n");
      out.write("\t \t\t\t\t\r\n");
      out.write("\t \t\t\t\t }\r\n");
      out.write("\t \t\t\t else\r\n");
      out.write("\t \t\t\t\t {\r\n");
      out.write("\t \t\t\t     alert(\"Sorry!!!!Details Not Available!!\");\r\n");
      out.write("\t \t\t\t\t }\r\n");
      out.write("\t \t\t\t\r\n");
      out.write("      \t\t}\r\n");
      out.write("      \t });\r\n");
      out.write("      \t \r\n");
      out.write("      \t \r\n");
      out.write("       }\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \t\r\n");
      out.write("\t</script>     \r\n");
      out.write("\t<script>\r\n");
      out.write("\t\r\n");
      out.write("\tfunction updateDetails1(){\r\n");
      out.write("\t\tvar student_id =$(\"#student_id\").val();\r\n");
      out.write("\t \r\n");
      out.write("\t   \t \r\n");
      out.write("\t\t var student_name =$(\"#student_name\").val();\r\n");
      out.write("\t\r\n");
      out.write("\t   \t \r\n");
      out.write("\t   \tvar student_department =$(\"#department\").val();\r\n");
      out.write("\t   \r\n");
      out.write("\t   \t \r\n");
      out.write("\t   \tvar year =$(\"#year\").val();\r\n");
      out.write("\t  \r\n");
      out.write("\t   \t \r\n");
      out.write("\t   \tvar mobile =$(\"#mobile\").val();\r\n");
      out.write("\t   \t\r\n");
      out.write("\t   \t \r\n");
      out.write("\t \tvar address =$(\"#address\").val();\r\n");
      out.write("\t   \t\r\n");
      out.write("\t   \t \r\n");
      out.write("\t \tvar email =$(\"#email\").val();\r\n");
      out.write("\t   \r\n");
      out.write("\t   \t \r\n");
      out.write("\t \t\r\n");
      out.write("\t   \t \r\n");
      out.write("\t   \t \r\n");
      out.write("\t   \t$.ajax({\r\n");
      out.write("\t   \t type:\"POST\",\r\n");
      out.write("  \t\t url : \"UserServlet\",\r\n");
      out.write("     \t\t data : {student_id:student_id,student_name:student_name,student_department:student_department,year:year,mobile:mobile,address:address,email:email , action:\"updateStudentDetails\"},\r\n");
      out.write("     \t\t success : function(data)\r\n");
      out.write("     \t\t{\r\n");
      out.write("     \t\t\t if(data==true)\r\n");
      out.write("\t \t\t\t\t {\r\n");
      out.write("     \t\t\t\t\r\n");
      out.write("\t \t\t\t\t\r\n");
      out.write("\t \t\t\talert(\"Details Updated Successfully!!\");\r\n");
      out.write("\t \t\t\t\t\r\n");
      out.write("\t \t\t\t\t }\r\n");
      out.write("\t \t\t\t else\r\n");
      out.write("\t \t\t\t\t {\r\n");
      out.write("\t \t\t\t     alert(\"Sorry!!!!Details Not Updated!!\");\r\n");
      out.write("\t \t\t\t\t }\r\n");
      out.write("\t \t\t\t\r\n");
      out.write("     \t\t}\r\n");
      out.write("     \t });\r\n");
      out.write("     \t \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("<title>Academic Education V2</title>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("ul li{\r\n");
      out.write("font-size:15px;\r\n");
      out.write("}\r\n");
      out.write("</style>     \r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"top\">\r\n");
      out.write("<!-- ################################################################################################ -->\r\n");
      out.write("<div class=\"wrapper row0\">\r\n");
      out.write("  <div id=\"topbar\" class=\"clear\"> \r\n");
      out.write("    <!-- ################################################################################################ -->\r\n");
      out.write("    <!-- ################################################################################################ --> \r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ################################################################################################ -->    \r\n");
      out.write("<!-- ################################################################################################ -->\r\n");
      out.write("<div class=\"wrapper row2\">\r\n");
      out.write("  <div class=\"rounded\">\r\n");
      out.write("    <nav id=\"mainav\" class=\"clear\"> \r\n");
      out.write("      <!-- ################################################################################################ -->\r\n");
      out.write("      <ul class=\"clear\">\r\n");
      out.write("        <li class=\"active\"><a href=\"adminAction.jsp\">Back</a></li>\r\n");
      out.write("         <li><a href=\"LogoutServlet\">Log out</a></li>\r\n");
      out.write("       <!--  <li><a href=\"login.jsp\">Admin Login</a></li>\r\n");
      out.write("        <li><a href=\"login.jsp\">Staff Login</a></li>\r\n");
      out.write("        <li><a href=\"login.jsp\">Student Login</a></li> -->\r\n");
      out.write("     <!--    <li><a href=\"#\">Log out</a></li> -->\r\n");
      out.write("      </ul>\r\n");
      out.write("      <!-- ################################################################################################ --> \r\n");
      out.write("    </nav>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ################################################################################################ --> \r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<!-- <form action=\"UserServlet\" method=\"POST\">  -->\r\n");
      out.write(" <div class=\"row\">\r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t                  <center><table border=\"1\" class=\"table \" style=\";width:500px;height:40px;font-size:25px;color:black;\" >\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr  style=\"height:40px;\" >\r\n");
      out.write("\t\t\t\t\t<!-- <th>FACULTY ID</th> -->\r\n");
      out.write("\t\t\t\t\t<th>FACULTY NAME</th>\r\n");
      out.write("\t\t\t\t\t<th>UPDATE</th>\r\n");
      out.write("\t\t\t\t    <th>DELETE</th>\r\n");
      out.write("\t\t\t\t\t<!-- <th>CONTACT NO</th>  -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</center>    \r\n");
      out.write("\t\t                 ");
      out.write("\r\n");
      out.write("\t\t\t\t       </div> \r\n");
      out.write("\t\t\t\t       \r\n");
      out.write("\t\t\t\t     \r\n");
      out.write("\t\t\t\t     \r\n");
      out.write("\t\t\t\t     \t <div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\r\n");
      out.write("    <div class=\"modal-dialog modal-md\">\r\n");
      out.write("    \r\n");
      out.write("     \r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\" style=\"background-color:#90125E  ;\">\r\n");
      out.write("           <button type=\"button\" class=\"close\" data-dismiss=\"modal\" >&times;</button> \r\n");
      out.write("          <center><h2><b style=\"font-size: 20px;\">STUDENT DETAILS</b></h2> </center>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body\" style=\"background-color:black  ;\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"form-group\" style=\"text-align:center;\"><br>\r\n");
      out.write("\t\t\t<table  style=\"color:black; border-color: black;\" >\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t   <!--  <td style=\"display:none;\">Student ID:</td><td> -->\r\n");
      out.write("\t\t    <input type=\"text\" style=\"display:none;\"  id=\"student_id\" name=\"student_id\" readonly=\"readonly\"></td></tr> \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr><td>Student Name:</td><td style=\"margin-top:-10px;\"><input type=\"text\"  id=\"student_name\"  name=\"student_name\" ></td></tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<tr><td>Department:</td><td><input type=\"text\"  id=\"department\"  name=\"department\" ></td></tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr><td>Year:</td><td><input type=\"text\"  id=\"year\"  name=\"year\" ></td></tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr><td>Mobile No:</td><td><input type=\"text\"  id=\"mobile\"  name=\"mobile\" ></td></tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr><td>Address:</td><td><input type=\"text\"  id=\"address\"  name=\"address\" ></td></tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr><td>Email ID:</td><td><input type=\"email\" id=\"email\" name=\"email\" ></td></tr>\r\n");
      out.write("\t\t\t<!-- &nbsp;\r\n");
      out.write("\t\t\t<tr><td>Password:</td><td><input type=\"text\"  id=\"password\"  name=\"password\" ></td></tr> -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</div><br>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t<center> <button type=\"button\" class=\"btn btn-primary\"  data-dismiss=\"modal\"  style=\"margin-bottom:20px;width:120px;\" onclick=\"updateDetails1()\">Update Details</button></center> </div><br>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("     \r\n");
      out.write(" </div></div></div>\r\n");
      out.write(" \r\n");
      out.write("<!--  \r\n");
      out.write("  <div class=\"modal fade\" id=\"myModal\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("      \r\n");
      out.write("        Modal Header\r\n");
      out.write("        <div class=\"modal-header\" style=\"background-color:  #996600;\">\r\n");
      out.write("          <h4 class=\"modal-title\"><b style=\"margin-left:160px;font-size:35px;\">Update Details</b></h4>\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        Modal body\r\n");
      out.write("        <div class=\"modal-body\" style=\"background-color:   #C7AB73;\">\r\n");
      out.write("         <form class=\"login\">\r\n");
      out.write("               \r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                 <label style=\"color:Black;\">Name:</label>   <input type=\"text\" autocomplete=\"off\" class=\"required form-control\"  name=\"teacher_name\" value=\"\" style=\"color:#660033;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <label style=\"color:Black;\">Phone No:</label>   <input type=\"text\" autocomplete=\"off\" class=\"required form-control\"  name=\"contact_no\" value=\"\" style=\"color:#660033;\">\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t\t <div class=\"form-group\">\r\n");
      out.write("                   <label style=\"color:Black;\">Email-Id:</label>  <input type=\"text\" autocomplete=\"off\" class=\"required form-control\"  name=\"email\" value=\"\" style=\"color:#660033;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                   <label style=\"color:Black;\">Password:</label>  <input type=\"password\" class=\"required form-control\"  name=\"password\" value=\"\" style=\"color:#660033;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label style=\"color:Black;\">Branch:</label> <input type=\"text\" autocomplete=\"off\" class=\"required form-control\"  name=\"branch\" value=\"\" style=\"color:#660033;\">\r\n");
      out.write("                </div>\r\n");
      out.write("               \r\n");
      out.write("                <div class=\"form-group\" style=\"background-color:   #C7AB73;\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-success btn-lg1 btn-block\" name=\"action\" value=\"\">Update</button>\r\n");
      out.write("                </div>\r\n");
      out.write("              \r\n");
      out.write("            </form>\r\n");
      out.write("\t\t\r\n");
      out.write("        </div>\r\n");
      out.write(" \r\n");
      out.write("    </div>\r\n");
      out.write("  </div> \r\n");
      out.write("\t\t\t\t      \r\n");
      out.write("\t\t          \r\n");
      out.write("\t\t\t\t      \r\n");
      out.write("\r\n");
      out.write("\t </div>       -->         \r\n");
      out.write("          \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("  \t\t       \r\n");
      out.write("    <!--    </form> \r\n");
      out.write("  -->\r\n");
      out.write("   <!-- JAVASCRIPTS --> \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /allstudentlist.jsp(235,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/allstudentlist.jsp(235,4) '${studentlist}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${studentlist}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /allstudentlist.jsp(235,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("user");
    // /allstudentlist.jsp(235,4) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVarStatus("count");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t<tr class=\"editField\">\r\n");
          out.write("\t\t\t\t\t<td id=\"studentID");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" style=\"display:none;\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.student_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.student_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t<td><a onclick=\"updateDetails(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(");\" >Update</a></td>\r\n");
          out.write("\t\t\t\t\t<td><a href=\"UserServlet?action=deleteStudent&student_id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.student_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">Delete</a></td>\r\n");
          out.write("\t\t\t\t\t");
          out.write("\r\n");
          out.write("\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
