/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2018-03-26 12:11:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--\r\n");
      out.write("Template Name: Academic Education V2\r\n");
      out.write("Author: <a href=\"http://www.os-templates.com/\">OS Templates</a>\r\n");
      out.write("Author URI: http://www.os-templates.com/\r\n");
      out.write("Licence: Free to use under our free template licence terms\r\n");
      out.write("Licence URI: http://www.os-templates.com/template-terms\r\n");
      out.write("-->\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Student Feedback System</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">\r\n");
      out.write("<link href=\"layout/styles/layout.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t .clear\r\n");
      out.write("\t{\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t} \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"top\">\r\n");
      out.write("<!-- ################################################################################################ --> \r\n");
      out.write("<!-- ################################################################################################ --> \r\n");
      out.write("<!-- ################################################################################################ -->\r\n");
      out.write("<div class=\"wrapper row0\">\r\n");
      out.write("  <div id=\"topbar\" class=\"clear\"> \r\n");
      out.write("    <!-- ################################################################################################ -->\r\n");
      out.write("    <!-- <nav>\r\n");
      out.write("      <ul>\r\n");
      out.write("        <li><a href=\"#\">Home</a></li>\r\n");
      out.write("        <li><a href=\"register.jsp\">Registration</a></li>\r\n");
      out.write("        <li><a href=\"login.jsp\">Login</a></li>\r\n");
      out.write("        <li><a href=\"LogoutServlet\">Log out</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </nav> -->\r\n");
      out.write("    <!-- ################################################################################################ --> \r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ################################################################################################ --> \r\n");
      out.write("<!-- ################################################################################################ --> \r\n");
      out.write("<!-- ################################################################################################ -->\r\n");
      out.write("<div class=\"wrapper row1\">\r\n");
      out.write("  <header id=\"header\" class=\"clear\"> \r\n");
      out.write("    <!-- ################################################################################################ -->\r\n");
      out.write("    <div id=\"logo\" class=\"fl_left\">\r\n");
      out.write("      <h1><a href=\"index.html\">Student Feedback System</a></h1>\r\n");
      out.write("      <p></p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- <div class=\"fl_right\">\r\n");
      out.write("      <form class=\"clear\" method=\"post\" action=\"#\">\r\n");
      out.write("        <fieldset>\r\n");
      out.write("          <legend>Search:</legend>\r\n");
      out.write("          <input type=\"text\" value=\"\" placeholder=\"Search Here\">\r\n");
      out.write("          <button class=\"fa fa-search\" type=\"submit\" title=\"Search\"><em>Search</em></button>\r\n");
      out.write("        </fieldset>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div> -->\r\n");
      out.write("    <!-- ################################################################################################ --> \r\n");
      out.write("  </header>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ################################################################################################ --> \r\n");
      out.write("<!-- ################################################################################################ --> \r\n");
      out.write("<!-- ################################################################################################ -->\r\n");
      out.write("<div class=\"wrapper row2\">\r\n");
      out.write("  <div class=\"rounded\">\r\n");
      out.write("    <nav id=\"mainav\" class=\"clear\"> \r\n");
      out.write("      <!-- ################################################################################################ -->\r\n");
      out.write("      <ul class=\"clear\">\r\n");
      out.write("        <li class=\"active\"><a href=\"home.jsp\">Home</a></li>\r\n");
      out.write("        <li><a href=\"adminlogin.jsp\">Admin Login</a></li>\r\n");
      out.write("        <li><a href=\"login.jsp\">Staff Login</a></li>\r\n");
      out.write("        <li><a href=\"studentlogin.jsp\">Student Login</a></li>\r\n");
      out.write("     <!--    <li><a href=\"#\">Log out</a></li> -->\r\n");
      out.write("      </ul>\r\n");
      out.write("      <!-- ################################################################################################ --> \r\n");
      out.write("    </nav>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ################################################################################################ --> \r\n");
      out.write("<!-- ################################################################################################ --> \r\n");
      out.write("<!-- ################################################################################################ -->\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("  <div id=\"slider\">\r\n");
      out.write("    <div id=\"slide-wrapper\" class=\"rounded clear\"> \r\n");
      out.write("      <!-- ################################################################################################ -->\r\n");
      out.write("      <figure id=\"slide-1\"><a class=\"view\" href=\"#\"><img src=\"images/banner_image.jpg\" alt=\"\"></a>\r\n");
      out.write("        <!-- <figcaption>\r\n");
      out.write("          <h2>Nullamlacus dui ipsum</h2>\r\n");
      out.write("          <p>Attincidunt vel nam a maurisus lacinia consectetus magnisl sed ac morbi. Inmaurisus habitur pretium eu et ac vest penatibus id lacus parturpis.</p>\r\n");
      out.write("          <p class=\"right\"><a href=\"#\">Continue Reading &raquo;</a></p>\r\n");
      out.write("        </figcaption> -->\r\n");
      out.write("      </figure>\r\n");
      out.write("      <figure id=\"slide-2\"><a class=\"view\" href=\"#\"><img src=\"images/demo/slider/2.png\" alt=\"\"></a>\r\n");
      out.write("        <figcaption>\r\n");
      out.write("          <h2> GPT</h2>\r\n");
      out.write("          <p>GPT is a government engineering college which is affiliated to the various undergraduate, post graduate and doctoral levels. </p>\r\n");
      out.write("         <p>DMCE's 2.47-acre campus is located in the suburb of Airoli in Navi Mumbai. The students have access to a fully computerized library maintaining around 40,000 books and journals. Students with vernacular backgrounds can improve their listening, reading, speaking and writing skills in English from the Language Lab. \r\n");
      out.write("         Other notable campus facilities includes seminar hall, gymnasium, canteen and a badminton court.</p> <p class=\"right\"><!-- <a href=\"\">Continue Reading &raquo;</a> --></p>\r\n");
      out.write("        </figcaption>\r\n");
      out.write("      </figure>\r\n");
      out.write("      <figure id=\"slide-3\"><a class=\"view\" href=\"#\"><img src=\"images/demo/slider/3.png\" alt=\"\"></a>\r\n");
      out.write("        <figcaption>\r\n");
      out.write("          <h2>OUR MOTO</h2>\r\n");
      out.write("          <p>\r\n");
      out.write("Our Motto is to address the critical needs of the society and foster economic development by nuturing \r\n");
      out.write("collaborative and friendly learning communities in which all stake holders can succeed and are involved in the continous \r\n");
      out.write("assesment and improvement process. We value academic excellence, professionalism, ethics and \r\n");
      out.write("cultural diversity among faculty, staff and students.</p>\r\n");
      out.write("          <p class=\"right\"></p>\r\n");
      out.write("        </figcaption>\r\n");
      out.write("      </figure>\r\n");
      out.write("      <figure id=\"slide-4\"><a class=\"view\" href=\"#\"><img src=\"images/demo/slider/4.png\" alt=\"\"></a>\r\n");
      out.write("        <figcaption>\r\n");
      out.write("          <h2>FACULTY DETAILS</h2>\r\n");
      out.write("          <p>\r\n");
      out.write("1. CIVIL ENGINEERING<br>\r\n");
      out.write("2. MECHANICAL ENGINEERING<br>\r\n");
      out.write("3. ELECTRONICS ENGINEERING<br>\r\n");
      out.write("4. COMPUTER ENGINEERING<br>\r\n");
      out.write("5. INFORMATION TECHNOLOGY<br>\r\n");
      out.write("6. CHEMICAL ENGINEERING<br>\r\n");
      out.write("7. HUMANITY AND SCIENCES (ENGINEERING) </p>\r\n");
      out.write("          <p class=\"right\"></p>\r\n");
      out.write("        </figcaption>\r\n");
      out.write("      </figure>\r\n");
      out.write("      <figure id=\"slide-5\"><a class=\"view\" href=\"#\"><img src=\"images/demo/slider/5.png\" alt=\"\"></a>\r\n");
      out.write("        <figcaption>\r\n");
      out.write("          <h2>STUDENT AND  ALUMNI & REVIEWS</h2>\r\n");
      out.write("          <p>AdityaBatch of 2016 Rating 2.8/5 Recommends this course\r\n");
      out.write("Course reviewed : B.E. in Information Technology\r\n");
      out.write("Good but can be best in placements.\r\n");
      out.write("Placements : Placements for civil are the best. Nothing for any other courses. Even BE computers placement is good. The average salary is 3.25 LPA. Companies visiting are TCS, L&T, Zycus and many more. Many students from various departments get opportunities but there are criteria which many do not fit in.\r\n");
      out.write("Infrastructure : Classrooms are wide open and good enough to seat 70 students. One of the best libraries in the Navi Mumbai college. Sadly, in this modern world, there's no Wi-Fi. They have medical facilities. There is only one annual sports event, but they don't allow you to practi...\r\n");
      out.write("         </p>\r\n");
      out.write("          <p class=\"right\"></p>\r\n");
      out.write("        </figcaption>\r\n");
      out.write("      </figure>\r\n");
      out.write("      <!-- ################################################################################################ -->\r\n");
      out.write("      <!-- <ul id=\"slide-tabs\">\r\n");
      out.write("        <li><a href=\"#slide-1\">Datta Meghe College</a></li>\r\n");
      out.write("        <li><a href=\"#slide-2\">All About College</a></li>\r\n");
      out.write("        <li><a href=\"#slide-3\">Our moto </a></li>\r\n");
      out.write("        <li><a href=\"#slide-4\">FACULTY DETAILS</a></li>\r\n");
      out.write("        <li><a href=\"#slide-5\">Student & Alumni Reviews &amp; Events</a></li>\r\n");
      out.write("      </ul> -->\r\n");
      out.write("      <!-- ################################################################################################ --> \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- JAVASCRIPTS --> \r\n");
      out.write("<script src=\"layout/scripts/jquery.min.js\"></script> \r\n");
      out.write("<script src=\"layout/scripts/jquery.fitvids.min.js\"></script> \r\n");
      out.write("<script src=\"layout/scripts/jquery.mobilemenu.js\"></script> \r\n");
      out.write("<script src=\"layout/scripts/tabslet/jquery.tabslet.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
